PUT  http://localhost:3003/api/blogs/62b92d348a61255b77dc7c02
Content-Type: application/json

{
    "title": "Postman is a good tool for testing a REST-api",
    "author": "wowo",
    "url": "http://www.google.com",
    "likes": 78855
}